/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nidoran;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author phi314
 */
public class DetailBuku extends javax.swing.JFrame {

    /**
     * Creates new form DetailBuku
     */
    public DetailBuku() {
        initComponents();
        setLocationRelativeTo(null);
        
        _temp_jenis.setVisible(false);
        
        
        loadDataKategori();
        loadData();
        loadDataJenis();
        
        
        
    }
    
    public void loadData() {
        try {
            Connection c = DbConnection.getConnection();
            Statement s = c.createStatement();
            String q = "SELECT * FROM buku WHERE id='" + Perpustakaan.id_buku +"' LIMIT 1";
            ResultSet r = s.executeQuery(q);
            
            if(r.next()){
                Object keterangan = r.getString("keterangan");
                Object kategori = r.getString("kategori");
                Object jenis = r.getString("jenis");
                Object lokasi = r.getString("lokasi");
                Object jumlah = r.getString("jumlah");
                Object kode_buku = r.getString("kode_buku");
                Object isbn = r.getString("isbn");
                Object judul = r.getString("judul");
                Object penerbit = r.getString("penerbit");
                Object penulis = r.getString("penulis");
                Object tahun = r.getString("tahun");
                Object sumber = r.getString("sumber");             
                
                _kodeKeterangan.setText(keterangan.toString().substring(0, 1));
                _kategori.setSelectedItem(kategori.toString());
                _temp_jenis.setText(jenis.toString());
                _lokasi.setSelectedItem(lokasi.toString());
                _jumlah.setText(jumlah.toString());
                _isbn.setText(isbn.toString());
                _judul.setText(judul.toString());
                _penerbit.setText(penerbit.toString());
                _penulis.setText(penulis.toString());
                _tahun.setText(tahun.toString());
                _sumber.setSelectedItem(sumber.toString());
                _kodeNomorBuku.setText(kode_buku.toString().substring(7));
            }
            
            
        } catch (SQLException e) {
            System.err.println(e);
        }
    } 
    
    public void loadDataKategori() {
        try {
            Connection c = DbConnection.getConnection();
            Statement s = c.createStatement();
            
            String q = "SELECT * FROM kategori ORDER BY kode ASC";
            
            ResultSet r = s.executeQuery(q);
                        
            while (r.next()) {
                _kategori.addItem(r.getString("kode") + " - " + r.getString("nama"));                
            }
            
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    
    public void loadDataJenis() {
        _jenis.removeAllItems();
        
        String kode_kategori = _kategori.getSelectedItem().toString().substring(0, 1);
        
        try {
            Connection c = DbConnection.getConnection();
            Statement s = c.createStatement();
            String q = "SELECT * FROM jenis WHERE kode_kategori='"+ kode_kategori +"'";
            
            ResultSet r = s.executeQuery(q);
            
            _jenis.addItem("- Pilih Jenis");
            while(r.next()){
                _jenis.addItem(r.getString("kode") + " - " + r.getString("nama"));
            }
            
            _jenis.setSelectedItem(_temp_jenis.getText());
            
        } catch (SQLException e) {
            System.err.println(e);
        }
    } 
    
    public String getKodeBuku() {
        String kodeBuku = "B" + _kodeKeterangan.getText() + _kodeKategori.getText() + _kodeJenis.getText() + _kodeRak.getText() + _kodeNomorBuku.getText();
        return kodeBuku;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _penulis = new javax.swing.JTextField();
        _penerbit = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        _kodeJenis = new javax.swing.JLabel();
        _jenis = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        _tahun = new javax.swing.JFormattedTextField();
        _prefixKode = new javax.swing.JLabel();
        _kodeKategori = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        _kodeNomorBuku = new javax.swing.JLabel();
        _kodeKeterangan = new javax.swing.JLabel();
        cancelUpdateButton = new javax.swing.JButton();
        _lokasi = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        _sumber = new javax.swing.JComboBox<>();
        _jumlah = new javax.swing.JTextField();
        _kategori = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        _kodeRak = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        _isbn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        _judul = new javax.swing.JTextField();
        _id = new javax.swing.JLabel();
        _temp_jenis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Buku");

        _penulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _penulisActionPerformed(evt);
            }
        });

        _penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _penerbitActionPerformed(evt);
            }
        });

        jLabel16.setText("Jumlah");

        _kodeJenis.setText("-");

        _jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Jenis" }));
        _jenis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                _jenisItemStateChanged(evt);
            }
        });
        _jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _jenisActionPerformed(evt);
            }
        });

        jLabel14.setText("Jenis");

        _tahun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));
        _tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _tahunActionPerformed(evt);
            }
        });

        _prefixKode.setText("B");

        _kodeKategori.setText("-");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        _kodeNomorBuku.setText("-");

        _kodeKeterangan.setText("-");

        cancelUpdateButton.setText("Batal");
        cancelUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelUpdateButtonActionPerformed(evt);
            }
        });

        _lokasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RA1 - IPA Kelas 1", "RA2 - IPA Kelas 2", "RA3 - IPA Kelas 3", "RS1 - IPS Kelas 1", "RS2 - IPS Kelas 2", "RS3 - IPS Kelas 3", "RB1 - Bahasa Kelas 1", "RB2 - Bahasa Kelas 2", "RB3 - Bahasa Kelas 3", "RU1 - Umum Kelas 1", "RU2 - Umum Kelas 2", "RU3 - Umum Kelas 3", " " }));
        _lokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _lokasiActionPerformed(evt);
            }
        });

        jLabel10.setText("Sumber");

        _sumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pembelian", "sumbangan" }));
        _sumber.setName("Update Buku"); // NOI18N
        _sumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sumberActionPerformed(evt);
            }
        });

        _kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Kategori" }));
        _kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _kategoriActionPerformed(evt);
            }
        });

        jLabel6.setText("Kategori");

        jLabel8.setText("Kode Buku");

        jLabel1.setText("ISBN");

        _kodeRak.setText("RA1");

        jLabel2.setText("Judul");

        jLabel3.setText("Penerbit");

        jLabel4.setText("Penulis");

        jLabel5.setText("Tahun");

        _isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _isbnActionPerformed(evt);
            }
        });

        jLabel7.setText("Rak");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_id, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16))
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel14))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(_prefixKode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_kodeKeterangan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_kodeKategori)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_kodeJenis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_kodeRak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_kodeNomorBuku))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(_penulis)
                                        .addComponent(_penerbit)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(_sumber, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(_temp_jenis))
                                            .addGap(0, 159, Short.MAX_VALUE))))))
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(_prefixKode)
                        .addComponent(_kodeKeterangan))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(_kodeNomorBuku)
                        .addComponent(_kodeKategori)
                        .addComponent(_kodeJenis)
                        .addComponent(_kodeRak)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_id, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(_penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_penulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(_sumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(_temp_jenis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(cancelUpdateButton))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _penulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__penulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__penulisActionPerformed

    private void _penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__penerbitActionPerformed

    private void _jenisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event__jenisItemStateChanged
        // TODO add your handling code here:
        // String kode_jenis = _jenis.getSelectedItem().toString().substring(1);
        //_kodeJenis.setText(kode_jenis);
    }//GEN-LAST:event__jenisItemStateChanged

    private void _jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__jenisActionPerformed
        // TODO add your handling code here:
        String kode_jenis = "-";
        if(_jenis.getItemCount() > 0) {
            kode_jenis = _jenis.getSelectedItem().toString().substring(0, 1);
        }

        _kodeJenis.setText(kode_jenis);
    }//GEN-LAST:event__jenisActionPerformed

    private void _tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__tahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__tahunActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:

        String id = Perpustakaan.id_buku;
        String isbn = _isbn.getText();
        String judul = _judul.getText();
        String penerbit = _penerbit.getText();
        String penulis = _penulis.getText();
        String tahun = _tahun.getText();
        String lokasi = _lokasi.getSelectedItem().toString();
        String kategori = _kategori.getSelectedItem().toString();
        String sumber = _sumber.getSelectedItem().toString();

        String kode_buku = getKodeBuku();

        try {
            Connection c = DbConnection.getConnection();

            String q = "UPDATE buku "
            + "SET "
            + "isbn=?,"
            + "judul=?,"
            + "penerbit=?,"
            + "penulis=?,"
            + "tahun=?,"
            + "kode_buku=?, "
            + "kategori=?, "
            + "sumber=?, "
            + "lokasi=? "
            + "WHERE id=?";

            PreparedStatement p = c.prepareStatement(q);

            p.setString(1, isbn);
            p.setString(2, judul);
            p.setString(3, penerbit);
            p.setString(4, penulis);
            p.setString(5, tahun);
            p.setString(6, kode_buku);
            p.setString(7, kategori);
            p.setString(8, sumber);
            p.setString(9, lokasi);
            p.setString(10, id);

            p.executeUpdate();
            p.close();

            JOptionPane.showMessageDialog(null, "Berhasil update buku dengan judul: " + judul, "Informasi", JOptionPane.WARNING_MESSAGE);
            dispose();
            new Buku().setVisible(true);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal update data buku", "Kesalahan", JOptionPane.WARNING_MESSAGE);
            System.out.println(e);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void cancelUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelUpdateButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new Buku().setVisible(true);
    }//GEN-LAST:event_cancelUpdateButtonActionPerformed

    private void _lokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__lokasiActionPerformed
        // TODO add your handling code here:
        String kode_keterangan = _lokasi.getSelectedItem().toString().substring(0, 3);
        _kodeRak.setText(kode_keterangan);;
    }//GEN-LAST:event__lokasiActionPerformed

    private void _sumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__sumberActionPerformed

    private void _kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__kategoriActionPerformed
        // TODO add your handling code here:
        String kode = _kategori.getSelectedItem().toString().substring(0, 1);
        _kodeKategori.setText(kode);

        loadDataJenis();
    }//GEN-LAST:event__kategoriActionPerformed

    private void _isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__isbnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _id;
    private javax.swing.JTextField _isbn;
    private javax.swing.JComboBox<String> _jenis;
    private javax.swing.JTextField _judul;
    private javax.swing.JTextField _jumlah;
    private javax.swing.JComboBox<String> _kategori;
    private javax.swing.JLabel _kodeJenis;
    private javax.swing.JLabel _kodeKategori;
    private javax.swing.JLabel _kodeKeterangan;
    private javax.swing.JLabel _kodeNomorBuku;
    private javax.swing.JLabel _kodeRak;
    private javax.swing.JComboBox<String> _lokasi;
    private javax.swing.JTextField _penerbit;
    private javax.swing.JTextField _penulis;
    private javax.swing.JLabel _prefixKode;
    private javax.swing.JComboBox<String> _sumber;
    private javax.swing.JFormattedTextField _tahun;
    private javax.swing.JLabel _temp_jenis;
    private javax.swing.JButton cancelUpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
