/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nidoran;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author phi314
 */
public class Pengembalian extends javax.swing.JFrame {
       
    private DefaultTableModel modelDetailPeminjaman = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    public int jumlah_buku = 0;

    /**
     * Creates new form Peminjaman
     */
    public Pengembalian() {
        initComponents();
        setLocationRelativeTo(null);
        
        fixIdMember.setVisible(false);
        
        /**
         * Table Detail Peminjaman
         */
        TableDetailPeminjaman.setModel(modelDetailPeminjaman);
        modelDetailPeminjaman.addColumn("_id");
        modelDetailPeminjaman.addColumn("ISBN");
        modelDetailPeminjaman.addColumn("Judul");
        modelDetailPeminjaman.addColumn("Penerbit");
        modelDetailPeminjaman.addColumn("Penulis");
        modelDetailPeminjaman.addColumn("Tahun");
        
        String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
        _tanggal_kembali.setText(timeStamp);
        
        TableDetailPeminjaman.removeColumn(TableDetailPeminjaman.getColumnModel().getColumn(0));

    }
    
    public void setFixJumlahBuku() {
        String jumlah_buku = Integer.toString(TableDetailPeminjaman.getRowCount());
        fixJumlahBuku.setText(jumlah_buku);
    }
    
    public void loadDataBuku(){
        modelDetailPeminjaman.getDataVector().removeAllElements();
        modelDetailPeminjaman.fireTableDataChanged();
     
        
        try
        {
            Connection c = DbConnection.getConnection();
            Statement s = c.createStatement();
            
            String sql = "SELECT *, detail_peminjaman.id as id_detail_peminjaman FROM detail_peminjaman JOIN buku ON buku.id=detail_peminjaman.id_buku WHERE detail_peminjaman.id_peminjaman='"+ Perpustakaan.id_peminjaman +"' ORDER BY buku.judul ASC";
            ResultSet r = s.executeQuery(sql);
            
            while(r.next())
            {
                Object[] o = new Object[6];
                o[0] = r.getString("id_buku");
                o[1] = r.getString("isbn");
                o[2] = r.getString("judul");
                o[3] = r.getString("penerbit");
                o[4] = r.getString("penulis");
                o[5] = r.getString("tahun");
                
                modelDetailPeminjaman.addRow(o);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    
    public void clear(){
        _kode.setText("");
        fixNomor.setText("-");
        fixTanggalPinjam.setText("-");
        fixNama.setText("-");
        fixKelas.setText("-");
        fixNis.setText("-");
        fixSubtotal.setText("-");
        Perpustakaan.id_peminjaman = "";
        
        modelDetailPeminjaman.getDataVector().removeAllElements();
        modelDetailPeminjaman.fireTableDataChanged();
        
        fixJumlahBuku.setText("0");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkOutButton = new javax.swing.JButton();
        fixIdMember = new javax.swing.JLabel();
        fixJumlahBuku = new javax.swing.JLabel();
        fixStatusBuku = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        _total = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        panelPeminjam = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        _kode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fixNis = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        checkNisButton = new javax.swing.JButton();
        fixNama = new javax.swing.JLabel();
        fixKelas = new javax.swing.JLabel();
        fixTanggalPinjam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fixSubtotal = new javax.swing.JTextField();
        fixDenda = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fixNomor = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        _tanggal_kembali = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDetailPeminjaman = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Peminjaman");

        checkOutButton.setText("Simpan");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        fixJumlahBuku.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        fixJumlahBuku.setText("0");

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PENGEMBALIAN BUKU");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel12.setText("Jumlah Buku");

        closeButton.setText("Batal");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        _total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _totalKeyTyped(evt);
            }
        });

        jLabel22.setText("Total Bayar");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setText("Kelas");

        jLabel6.setText("Kode Peminjaman");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel10.setText("Tanggal Pinjam");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("Nama");

        fixNis.setText("-");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("NIS");

        checkNisButton.setText("Cek");
        checkNisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNisButtonActionPerformed(evt);
            }
        });

        fixNama.setText("-");

        fixKelas.setText("-");

        fixTanggalPinjam.setText("-");

        jLabel1.setText("Data Peminjam");

        jLabel24.setText("Rp.");

        jLabel27.setText("Rp.");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setText("Denda");

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel13.setText("Subtotal");

        jLabel2.setText("Data Peminjaman");

        fixSubtotal.setText("0");
        fixSubtotal.setEnabled(false);

        fixDenda.setText("0");
        fixDenda.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel14.setText("Nomor Member");

        fixNomor.setText("-");

        javax.swing.GroupLayout panelPeminjamLayout = new javax.swing.GroupLayout(panelPeminjam);
        panelPeminjam.setLayout(panelPeminjamLayout);
        panelPeminjamLayout.setHorizontalGroup(
            panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeminjamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkNisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPeminjamLayout.createSequentialGroup()
                .addGroup(panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPeminjamLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(panelPeminjamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(fixNomor)))
                    .addGroup(panelPeminjamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(fixNis)))
                    .addGroup(panelPeminjamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(fixKelas)))
                    .addGroup(panelPeminjamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(fixNama))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(fixTanggalPinjam)
                    .addComponent(jLabel13)
                    .addGroup(panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPeminjamLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fixSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPeminjamLayout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fixDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, 65))
        );
        panelPeminjamLayout.setVerticalGroup(
            panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeminjamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPeminjamLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addGroup(panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkNisButton)))
                .addGap(30, 30, 30)
                .addGroup(panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPeminjamLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fixNis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(fixNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fixKelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fixNomor))
                    .addGroup(panelPeminjamLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fixTanggalPinjam)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel11)
                        .addGap(19, 19, 19)
                        .addGroup(panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(fixDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(fixSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLabel26.setText("Rp.");

        jLabel25.setText("(yyyy-mm-dd)");

        _tanggal_kembali.setEnabled(false);

        jLabel28.setText("Tanggal Kembali");

        TableDetailPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TableDetailPeminjaman);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fixStatusBuku)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fixIdMember))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_tanggal_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel25))
                    .addComponent(jLabel22)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(12, 12, 12)
                        .addComponent(_total, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fixJumlahBuku)
                    .addComponent(jLabel12)
                    .addComponent(checkOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fixStatusBuku)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fixIdMember))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel28)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_tanggal_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel25)))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel22)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel26))
                            .addComponent(_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel12)
                                .addGap(4, 4, 4)
                                .addComponent(fixJumlahBuku)
                                .addGap(26, 26, 26)
                                .addComponent(checkOutButton)
                                .addGap(6, 6, 6)
                                .addComponent(closeButton))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkNisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNisButtonActionPerformed
        // TODO add your handling code here:
        
        try {
            Connection c = DbConnection.getConnection();
            
            String q = "SELECT peminjaman.*, member.nama, member.nis, member.nomor, member.kelas FROM peminjaman "
                    + "JOIN member ON member.id=peminjaman.id_member "
                    + "WHERE peminjaman.kode=? LIMIT 1";
            
            PreparedStatement p = c.prepareStatement(q);
            
            p.setString(1, _kode.getText());
            
            ResultSet r = p.executeQuery();
            
            if(r.next()){
                if(r.getString("status").equals("pinjam"))
                {
                    Perpustakaan.id_peminjaman = r.getString("id");
                    fixNomor.setText(r.getString("nomor"));
                    fixNis.setText(r.getString("nis"));
                    fixNama.setText(r.getString("nama"));
                    fixKelas.setText(r.getString("kelas"));
                    fixTanggalPinjam.setText(r.getString("tanggal"));
                    fixSubtotal.setText(r.getString("subtotal"));
                    
                    int subtotal = r.getInt("subtotal") + Perpustakaan.countDenda(r.getString("tanggal"));
                    String string_subtotal = Integer.toString(subtotal);
                    String string_denda = Integer.toString(Perpustakaan.countDenda(r.getString("tanggal")));
                    
                    fixDenda.setText(string_denda);
                    fixSubtotal.setText(string_subtotal);

                    p.close();

                    loadDataBuku();
                    setFixJumlahBuku();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Peminjaman dengan kode "+_kode.getText()+", sudah kembali.", "Kesalahan", JOptionPane.WARNING_MESSAGE);
                    clear();
                }
                
            }
            else {
                
                JOptionPane.showMessageDialog(this, "Member tidak ditemukan, Silahkan daftarkan member.", "Kesalahan", JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_checkNisButtonActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        // TODO add your handling code here:
        
        try {

            
            Boolean update = true;
            String message = null;
            
            if(Perpustakaan.id_peminjaman.equals("")){
                update = false;
                message = "Member peminjam belum ada.";
            }           
            else
            if(_total.getText().equals("")){
                update = false;
                message = "Total bayar belum diisi.";
                _total.setFocusable(true);
            }
            else
            if(Integer.parseInt(_total.getText()) < Integer.parseInt(fixSubtotal.getText())){
                update = false;
                message = "Jumlah total bayar kurang dari subtotal.";
                _total.setFocusable(true);
            }
            
            int denda = Integer.parseInt(fixDenda.getText());
            int bayar = Integer.parseInt(_total.getText());

            int kembali = bayar - denda;
            
            if(update) {
                 // insert into peminjaman
                Connection c = DbConnection.getConnection();
                Statement s = c.createStatement();
                String qInsertPeminjaman = "UPDATE peminjaman SET tanggal_kembali='"+_tanggal_kembali.getText()+"', denda='"+fixDenda.getText()+"', total_bayar='"+_total.getText()+"', kembali='"+kembali+"', status='kembali' WHERE id='"+ Perpustakaan.id_peminjaman +"'";               
                
                s.executeUpdate(qInsertPeminjaman);
               
                s.close();
                
                String qUpdateBuku = "UPDATE buku SET is_tersedia='1', id_peminjaman=NULL WHERE id=? ";
                PreparedStatement pUpdateBuku = c.prepareStatement(qUpdateBuku);
                
                for(int i = 0; i < modelDetailPeminjaman.getRowCount(); i++) {
                    String id_buku = modelDetailPeminjaman.getValueAt(i, 0).toString();

                    pUpdateBuku.setString(1, id_buku);
                    pUpdateBuku.executeUpdate();                    
                }

                pUpdateBuku.close();
                
                JOptionPane.showMessageDialog(this, "Berhasil Tambah Pengembalian.", "Informasi", JOptionPane.WARNING_MESSAGE);
                setVisible(false);
                dispose();
                
                new HomeFront().setVisible(true);
                
                if(Integer.parseInt(_total.getText()) > 0)
                {
                     // TODO add your handling code here:
                    File file = new File("./report/detailDenda.jasper");
                    try {
                        JasperReport jasperReport = (JasperReport) JRLoader.loadObject(file);
                        Map parametersMap = new HashMap();  
                        parametersMap.put("id_peminjaman", Perpustakaan.id_peminjaman);
                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametersMap, c);
                        net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);

                    } catch (JRException ex) {
                        javax.swing.JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                    }
                }
                
                
                
            }
            else {
                JOptionPane.showMessageDialog(this, message, "Kesalahan", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        
        new HomeFront().setVisible(true);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void _totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__totalKeyTyped
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event__totalKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDetailPeminjaman;
    private javax.swing.JTextField _kode;
    private javax.swing.JTextField _tanggal_kembali;
    private javax.swing.JTextField _total;
    private javax.swing.JButton checkNisButton;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField fixDenda;
    private javax.swing.JLabel fixIdMember;
    private javax.swing.JLabel fixJumlahBuku;
    private javax.swing.JLabel fixKelas;
    private javax.swing.JLabel fixNama;
    private javax.swing.JLabel fixNis;
    private javax.swing.JLabel fixNomor;
    private javax.swing.JLabel fixStatusBuku;
    private javax.swing.JTextField fixSubtotal;
    private javax.swing.JLabel fixTanggalPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelPeminjam;
    // End of variables declaration//GEN-END:variables
}
